use_frameworks!
platform :osx, '10.12'

target 'FLScene_Example' do
  pod 'FLScene', :path => '../'
  pod 'FLGame', :path => '~/dev/floats/FLGame'
  pod 'SKSwiftLib', :path => '~/dev/ios/SKLibs/SKSwiftLib'

  target 'FLScene_Tests' do
    inherit! :search_paths

    
  end
end
